openapi: 3.0.1
info:
    title: book-service
    description: This is a sample book microservice
    version: 1.0.0
servers:
    - url: localhost
paths:
    /api/book/{id}:
        get:
            tags:
                - book
            summary: get a single book by id
            operationId: getbook
            parameters:
                - $ref: '#/components/parameters/id'
            responses:
                200:
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    data:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/BookData'
                400:
                    description: unsuccesful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    errors:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Errors'

    /api/book/all:
        get:
            tags:
                - book
            summary: retrieve all book from database
            operationId: getAllbooks
            responses:
                200:
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    data:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/BookData'

                400:
                    description: unsuccesful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    errors:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Errors'
    /api/book/destroy:
        post:
            tags:
                - book
            summary: delete a book by id
            operationId: deletebook
            requestBody:
                description: delete book from the backend
                required: true
                content:
                    application/json:
                        schema:
                            properties:
                                id:
                                    type: string
            responses:
                202:
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    data:
                                        type: boolean

                400:
                    description: unsuccesful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    errors:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Errors'
    /api/book/add:
        post:
            tags:
                - book
            summary: add a book
            operationId: addbook
            requestBody:
                description: add book to the backend
                required: true
                content:
                    application/json:
                        schema:
                            properties:
                                _id:
                                    type: string
                                name:
                                    type: string
                                bookAuthor:
                                    nullable: true
                                    type: string
                                bookVersion:
                                    nullable: true
                                    type: number
                                learningStatus:
                                    type: number
                                languages:
                                    type: array
                                    nullable: true
                                    items:
                                        $ref: '#/components/schemas/LanguageData'
                                skills:
                                    type: array
                                    nullable: true
                                    items:
                                        $ref: '#/components/schemas/SkillData'

            responses:
                201:
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    data:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/BookData'

                400:
                    description: unsuccesful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    errors:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Errors'
    /api/book/update:
        post:
            tags:
                - course
            summary: edit a course
            operationId: EditCourse
            requestBody:
                description: edit course data in the backend
                required: true
                content:
                    application/json:
                        schema:
                            properties:
                                _id:
                                    type: string
                                name:
                                    type: string
                                bookAuthor:
                                    nullable: true
                                    type: string
                                bookVersion:
                                    nullable: true
                                    type: number
                                learningStatus:
                                    type: number
                                languages:
                                    type: array
                                    nullable: true
                                    items:
                                        $ref: '#/components/schemas/LanguageData'
                                skills:
                                    type: array
                                    nullable: true
                                    items:
                                        $ref: '#/components/schemas/SkillData'

            responses:
                201:
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    data:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/BookData'

                400:
                    description: unsuccesful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    errors:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Errors'
components:
    parameters:
        id:
            name: id
            in: path
            description: course Id values that need to be considered for filter
            required: true
            schema:
                type: string
    schemas:
        Errors:
            type: object
            properties:
                message:
                    type: string
                field:
                    nullable: true
                    type: string
        BookData:
            type: object
            properties:
                _id:
                    type: string
                name:
                    type: string
                version:
                    type: number
                bookAuthor:
                    type: string
                    nullable: true
                bookVersion:
                    type: number
                    nullable: true
                learningStatus:
                    type: number
                skillId:
                    type: array
                    items:
                        type: string
                languageId:
                    type: array
                    items:
                        type: string

        LanguageData:
            type: object
            nullable: true
            properties:
                _id:
                    type: string
                name:
                    type: string

        SkillData:
            type: object
            nullable: true
            properties:
                _id:
                    type: string
                name:
                    type: string
