apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: areebaiftikhar/course:v1
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: studyplan
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PORT
              value: "3000"
            - name: MONGO_DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: course-mongodb-uri
                  key: URI
---
apiVersion: v1
kind: Service
metadata:
  name: course-srv
spec:
  selector:
    app: course
  ports:
    - name: course
      protocol: TCP
      port: 3000
      targetPort: 3000
