apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill
  template:
    metadata:
      labels:
        app: skill
    spec:
      containers:
        - name: skill
          image: areebaiftikhar/skill:v2
          env:
            # this variabel will shift for production
            - name: NODE_ENV
              value: "development"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: studyplan
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PORT
              value: "3000"
            - name: MONGO_DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: skill-mongodb-uri
                  key: URI
            - name: JWT
              valueFrom:
                secretKeyRef:
                  name: jwtkey
                  key: JWTKEY
---
apiVersion: v1
kind: Service
metadata:
  name: skill-srv
spec:
  selector:
    app: skill
  ports:
    - name: skill
      protocol: TCP
      port: 3000
      targetPort: 3000
